CREATE TABLE mytable(
   sohampanda1gmailcom VARCHAR(33) NOT NULL PRIMARY KEY
);
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('Harshilgoyal73@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('anika.kamuni@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('akalwadmath@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('savvybray000@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('subhimani3672@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('Ashok.anukta@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('ariyanamorani0923@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('manaswimantena@gmail.con');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('rhesachander@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('25aalishha25@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('paishwarya1202@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('email7akshara@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('tshreeya2@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('manaswimantena@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('ananyajha0828@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('parellageethika@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('caroline.claire.jackson@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('florenceesantoss@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('Shanmukhsusrut@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('mahatikrishna01@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('subhimani3672@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('manaswimantena@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('sophiaseolee@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('jaiswaljiya18@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('nehmat1113@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('rizvihadeeqa@gmail.com');
INSERT INTO mytable(sohampanda1gmailcom) VALUES ('apitareese@gmail.com');
